CREATE TABLE PACIENTE(
PACIENTE_ID SERIAL NOT NULL,
CEDULA char(10) NULL,
NOMBRE char(30) NULL,
FECHA_NACIMIENTO date NULL,
ESTATURA int NULL,
PESO int NULL,
CONSTRAINT PK_PACIENTE PRIMARY KEY (PACIENTE_ID));

CREATE TABLE MEDICO(
MEDICO_ID SERIAL NOT NULL,
CEDULA char(10) NULL,
NOMBRE char(50) NOT NULL,
CORREO char(50) NOT NULL,
CODIGO char(10) NULL,
CONSTRAINT PK_MEDICO PRIMARY KEY (MEDICO_ID ) );

CREATE TABLE TERAPIA(
TERAPIA_ID SERIAL NOT NULL,
PACIENTE_ID int NOT NULL,
MEDICO_ID int NOT NULL,
FECHA timestamp NOT NULL,
DURACION int NULL,
OBSERVACION char(50) NOT NULL,
REALIZADA boolean NOT NULL DEFAULT FALSE,
CONSTRAINT PK_TERAPIA PRIMARY KEY (TERAPIA_ID) );

ALTER TABLE TERAPIA
ADD CONSTRAINT FK_TERAPIA_PACIENTE FOREIGN KEY(PACIENTE_ID)
REFERENCES PACIENTE (PACIENTE_ID)
ON DELETE restrict ON UPDATE restrict;

ALTER TABLE TERAPIA 
ADD CONSTRAINT FK_TERAPIA_MEDICO FOREIGN KEY(MEDICO_ID)
REFERENCES MEDICO (MEDICO_ID)
ON DELETE restrict ON UPDATE restrict;